on:
  workflow_dispatch:
    inputs:
      tag_version:
        type: string
        description: "The new version of the release."
        required: true

jobs:
  update_version:
    runs-on: ubuntu-latest
    name: Update Version
    steps:
      - uses: actions/checkout@v3
      - name: Setup Account
        run: |
          git config user.name $(git log -n 1 --pretty=format:%an)
          git config user.email $(git log -n 1 --pretty=format:%ae)
      - name: Write Version
        run: |
          if [[ ! "${{ github.event.inputs.tag_version }}" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "Invalid version ${{ github.event.inputs.tag_version }}"
            exit 1
          fi
          echo "${{ github.event.inputs.tag_version }}" > ./version/.VERSION
      - name: Create Tag
        run: |
          git switch -c release/${{ github.event.inputs.tag_version }}
          git commit -am "Version release ${{ github.event.inputs.tag_version }}"
          git push -u origin release/${{ github.event.inputs.tag_version }}
          git tag -a -m "Version release ${{ github.event.inputs.tag_version }}" ${{ github.event.inputs.tag_version }}
          git push origin ${{ github.event.inputs.tag_version }}
